### ISSUE TITLE
cant build

### ISSUE THREAD

**Issue by valvhammer** [lajp/dev_rickroll#1]
cannot build because of error:
```
make[1]: *** /lib/modules/5.16.14-artix1-1/build: No such file or directory. Stop
```
while i do know what the error means, i dont know why i need ` /lib/modules/5.16.14-artix1-1/build` 

gimme a fix

**Comment by lajp** [comment]
I only noticed this now. Compiling kernel modules requires the correct headers to be installed.
Try installing the `linux-xanmod-headers` from the AUR or something that has the headers for your kernel version.

**Comment by Zaedus** [comment]
For arch, all you need is the `linux-headers` library.

**Comment by lajp** [comment]
Oh yes, correct. I myself am using the xanmod kernel and got a bit confused :)

**Comment by eaxly** [comment]
I have installed `linux-headers` on my arch system, but still get this error:
```
make -C /lib/modules/5.16.15-arch1-1/build M=/home/USERNAME/dl/git/dev_rickroll modules
make[1]: Entering directory '/usr/lib/modules/5.16.15-arch1-1/build'
make[1]: *** No rule to make target 'modules'.  Stop.
make[1]: Leaving directory '/usr/lib/modules/5.16.15-arch1-1/build'
make: *** [Makefile:8: all] Error 2
```

**Comment by lajp** [comment]
If you've just recently installed the headers it might be that the kernel you are running is older than the header. I suggest you to try updating the system and then rebooting.

**Comment by eaxly** [comment]
Thanks, it works perfectly now!

**Comment by lajp** [comment]
Ok, good to hear. I'll be closing this issue now. If further problems appear just go ahead and open a new one.

**Comment by kqvanity** [comment]
@eaxly I faced the same issue as yous and the kernel headers package was available at APT the repos under `linux-headers-$(uname -r)`
