### ISSUE TITLE
Error when playing with aplay

### ISSUE THREAD

**Issue by nemalex** [lajp/dev_rickroll#3]
When I'm trying to open the device with aplay I'm getting the following error:
```
ALSA lib pcm_dmix.c:1032:(snd_pcm_dmix_open) unable to open slave
aplay: main:831: audio open error: No such file or directory
```

**Comment by lajp** [comment]
This is odd, I remember getting similar errors with aplay when it didn't have permissions to read from the device. Have you checked that the device is readable to aplay?

**Comment by nemalex** [comment]
With a bit of research I found that having a .asoundrc file in my home directory prevents the error happening. Altough now i got the following:
```
Playing raw data '/dev/rickroll' : Unsigned 8 bit, Rate 8000 Hz, Mono
aplay: set_params:1352: Sample format non available
Available formats:
- S16_LE
- S32_LE
```

Specifying one of these formats gives the message:
```
Playing raw data '/dev/rickroll' : Signed 32 bit Little Endian, Rate 8000 Hz, Mono
aplay: set_params:1358: Channels count non available
```

And for some strange reason aplay doesn't let me specify only one channel explicitly.
After specifíing 2 channels, I got whitenoise with both of the above formats. So aplay probably able to read the device.

**Comment by lajp** [comment]
The correct format is u8 8000Hz. For me aplay just recognizes it out of the box. What is the output of aplay when you try specifying the format manually like this:
```sh
aplay --format U8 -r 8 /dev/rickroll
```
Additionally you could try catting the output into aplay if that makes a difference:
```sh
cat /dev/rickroll | aplay
```

**Comment by nemalex** [comment]
I'm not sure why, but with the following .asoundrc I was able to play it:
```
pcm.!default {
  type plug
  slave {
    pcm "hw:1,0"
  }
}

ctl.!default {
    type hw
    card 1
}
```
Thanks for helping me out!
