### ISSUE TITLE
[Improve] Use make flags variables in Makefile files whenever possible.

### ISSUE THREAD

**Issue by VergeDX** [lajp/dev_rickroll#4]
I'm trying to package this kernel module on NixOS for fun,
then I noticed Makefile use absolute path instead of a variable.

And here is a Makefile example: https://github.com/dev47apps/droidcam/blob/v1.6/linux/v4l2loopback/Makefile
Use variable like `KERNELRELEASE`, `KERNEL_DIR`, `PWD` can improve portability, I can help to making PR!

**Comment by lajp** [comment]
This is cool. Nix is something I'm a fan of myself. Are you willing to make a PR out of this?

**Comment by lajp** [comment]
Ah, it seems you already did. Merged. Thank you once again for your contribution!
